import React from 'react';
import { 
  Home, 
  FileText, 
  Users, 
  Bot, 
  BarChart2, 
  Layers, 
  Database, 
  Map, 
  Search, 
  Plus, 
  Upload, 
  Download, 
  Edit, 
  Copy, 
  Trash2, 
  ChevronRight, 
  ChevronDown,
  FolderOpen,
  Folder,
  MoreHorizontal,
  Settings,
  Bell,
  LayoutGrid,
  Bookmark,
  CheckCircle,
  Slash,
  Code,
  Save,
  Scale,
  ArrowLeft,
  Check,
  MoreVertical,
  AlertCircle,
  History,
  Link2,
  Server,
  Globe,
  Wifi,
  WifiOff,
  GitBranch,
  Activity,
  Calendar,
  Clock,
  FileJson,
  Filter,
  Eye,
  RefreshCw
} from 'lucide-react';

export const Icons = {
  Home, FileText, Users, Bot, BarChart2, Layers, Database, Map, Search,
  Plus, Upload, Download, Edit, Copy, Trash2, ChevronRight, ChevronDown,
  FolderOpen, Folder, MoreHorizontal, Settings, Bell, LayoutGrid, Bookmark,
  CheckCircle, Slash, Code, Save, Scale, ArrowLeft, Check, MoreVertical, AlertCircle,
  History, Link2, Server, Globe, Wifi, WifiOff, GitBranch, Activity, Calendar, Clock,
  FileJson, Filter, Eye, RefreshCw
};